language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec

 deploy:
  provider: heroku
  api_key: c8e8548f-ecba-4107-a6b2-a3812cbfcb13
  app: jennas-art
  run: "rake db:migrate"